# Generated by Django 5.2.6 on 2025-09-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210610_1442'),
    ]

    operations = [
        migrations.RunSQL(
            """
            insert into store_collection (title)
            values('collection2')
            """,
            """
            delete from store_collection
            where title = 'collection2'
            """
        )
    ]
